name: ci_cd
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log Start Execute
        if: always()
        run: |
          echo "Starting execute: " $(date) >> ${{ github.workspace }}/log.txt
          echo "Submitters: Nave Maor, Eran Yosefia" >> ${{ github.workspace }}/log.txt
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: assignment3:latest, ${{ secrets.DOCKER_COURSE_USERNAME }}/assignment3:latest
          outputs: type=docker,dest=/tmp/image.tar
      - name: Success Build
        if: success()
        run: |
          echo "image successfully built" >> ${{ github.workspace }}/log.txt
      - name: Failed Build
        if: failure()
        run: |
          echo "image not able to be built" >> ${{ github.workspace }}/log.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: assignment3
          path: /tmp/image.tar
      - name: Upload Log File
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: LogFile
          path: ${{ github.workspace }}/log.txt
